services:
  - type: web
    name: tsukuba-pss
    runtime: docker
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BASIC_AUTH_USERS
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
